
NI-RFSA Python API Status
-------------------------

+-------------------------------+-----------------------+
| NI-RFSA (nirfsa)              |                       |
+===============================+=======================+
| Driver Version Tested Against | 21.5.0                |
+-------------------------------+-----------------------+
| PyPI Version                  | |nirfsaLatestVersion| |
+-------------------------------+-----------------------+
| Supported Python Version      | |nirfsaPythonVersion| |
+-------------------------------+-----------------------+
| Open Issues                   | |nirfsaOpenIssues|    |
+-------------------------------+-----------------------+
| Open Pull Requests            | |nirfsaOpenPRs|       |
+-------------------------------+-----------------------+


.. |nirfsaLatestVersion| image:: http://img.shields.io/pypi/v/nirfsa.svg
    :alt: Latest NI-RFSA Version
    :target: http://pypi.python.org/pypi/nirfsa


.. |nirfsaPythonVersion| image:: http://img.shields.io/pypi/pyversions/nirfsa.svg
    :alt: NI-RFSA supported Python versions
    :target: http://pypi.python.org/pypi/nirfsa


.. |nirfsaOpenIssues| image:: https://img.shields.io/github/issues/ni/nimi-python/nirfsa.svg
    :alt: Open Issues + Pull Requests for NI-RFSA
    :target: https://github.com/ni/nimi-python/issues?q=is%3Aopen+is%3Aissue+label%3Anirfsa


.. |nirfsaOpenPRs| image:: https://img.shields.io/github/issues-pr/ni/nimi-python/nirfsa.svg
    :alt: Pull Requests for NI-RFSA
    :target: https://github.com/ni/nimi-python/pulls?q=is%3Aopen+is%3Aissue+label%3Anirfsa


